# -*- coding: utf-8 -*-
"""Wheeled Mobility RGP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168ozZIvEMuK5nZNAT-DhD-2up7zYT3q9
"""

import numpy as np
import matplotlib.pyplot as plt

g = 9.82
m = 100
theta = 30

lf = np.arange(0.25, 1.76, 0.25)
lr = 2 - lf
h = np.arange(0.5, 2.01, 0.25)

plt.figure(figsize=(10,10))
for i in h:
    amax = g * (np.sin(theta) - np.cos(theta) * lf / i)
    plt.plot(lf, amax, label="h = " + str(i))

plt.ylabel("Deceleration")
plt.xlabel("$l_f$")
plt.legend()

